language: java

jdk: openjdk8

cache:
directories:
  - $HOME//Users/admin/Documents/PROGRAMMING/RESSOURCE/MAVEN

install: true
script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)