language: java

jdk: openjdk8

cache:
directories:
  - $HOME//Users/admin/Documents/PROGRAMMING/RESSOURCE/MAVEN

install: true

services:
  - postgresql

before_script:
  - psql -c 'create database db_myerp;' -U postgres
  - psql db_myerp < createDatabase.sql


script:
  - mvn clean install -P integration-test-business,integration-test-consumer

after_success:
  - bash <(curl -s https://codecov.io/bash)