language: java

jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - CODECOV_TOKEN="2f02aa5a-e627-44b0-9b1d-c7595b210c50"

install: true

services:
  - postgresql

before_script:
  - psql -c 'create database db_myerp;' -U postgres
  - psql db_myerp < createDatabase.sql


script:
  - mvn clean install -P integration-test-business,integration-test-consumer

after_success:
  - bash <(curl -s https://codecov.io/bash)